modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "bold_font_fix"
version = "${version}"
displayName = "Bold Font Fix"
authors = "Rain_G"
description = '''
Fix the bold issue of custom fonts
'''
#logoFile = ""

[[dependencies.bold_font_fix]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bold_font_fix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "bold_font_fix.mixins.json"
